# Numpy

* Python에서 대규모 다차원 배열을 다룰 수 있게 도와주는 라이브러리
* 데이터의 대부분은 숫자 배열로 확인 가능
* 반복문 없이 배열 처리가 가능
* 파이썬의 List에 비해 빠른 연산을 지원
* 파이썬의 List에 비해 메모리를 효율적으로 사용 가능

In [3]:
# numpy 라이브러리를 포함시킨다. - 쉽게 사용하기 위해 'np'라는 약어로 설정
import numpy as np

In [5]:
list_arr = list(range(5))
np_arr = np.arange(5)

In [11]:
# 결과를 보면, 비슷해보이지만, List는 콤바(,)로 구분이 되어있으며, 넘파일 배열은 공백으로 구분되어있음
print(list_arr, type(list_arr))
print(np_arr, type(np_arr))

[0, 1, 2, 3, 4] <class 'list'>
[0 1 2 3 4] <class 'numpy.ndarray'> int32


In [10]:
# np.arange(5)랑 똑같이 배열이 생성된다.
arr = np.array([0,1,2,3,4])
# dtype을 이용하여, 해당 배열의 데이터 타입을 확인할 수 있다.
print(arr, arr.dtype)

[0 1 2 3 4] int32


In [12]:
# 배열 생성시, 원하는 데이터 타입으로 지정이 가능하다.
arr = np.array([0,1,2,3,4], dtype=float)
# 결과를 보면, int32와는 다르게 요소뒤에 점이 붙어있는 모습(실수형 타입)을 확인할 수 있다.
print(arr, arr.dtype)

[0. 1. 2. 3. 4.] float64


In [13]:
# ndim = 배열의 차원 수 or 배열의 축 수
# shape = 배열의 각 차원의 크기를 튜플(tuple)로 표현
print(arr.ndim)
print(arr.shape)

1
(5,)


In [21]:
# 2 차원 배열 (matrix)
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)
print(arr_2.ndim)
print(arr_2.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [23]:
# size = 배열의 요소의 수
# len() = 배열의 길이 - 행(가로)의 길이
print('arr size : {}'.format(arr.size))
print('arr_2 size : {}'.format(arr_2.size))
print('len(arr) : {}'.format(len(arr)))
print('len(arr_2) : {}'.format(len(arr_2)))

arr size : 5
arr_2 size : 6
len(arr) : 5
len(arr_2) : 2


In [5]:
# 차원을 변경하여 모양을 바꿀 수 있다.
arr_3 = np.arange(1,10)
arr_3.shape = 3,3
arr_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# 생셩할때 차원의 모양을 바꿀수도 있다.
arr_4 = np.arange(1,10).reshape(3,3)
arr_4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])