In [1]:
import numpy as np

In [4]:
x = np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [5]:
# 인덱스로 값을 찾아내는 방법 (인덱스틑 0에서부터 시작)
x[3]

4

In [7]:
# 인덱싱을 활용하여 원하는 위치의 값을 변경할 수 있음
x[0] = 7
x[3] = 10
print(x)

[ 7  2  3 10  5  6]


In [14]:
# n차원 배열또한 인덱스로 원하는값을 찾아낼 수 있다.
y = np.arange(1,16,1)
y.shape = 3,5
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
y[1,2]

8

In [35]:
# 배열의 일부를 가져오기 위해서는 slicing를 활용
# 1차원 배열 slicing
z = np.arange(10)
print("배열의 전체 조회 : {}".format(z[:]))
print("인덱스 1 이상 5 미만의 요소 조회 : {}".format(z[1:5]))
print("배열의 길이를 모를경우, 마지막 값 조회 : {}".format(z[-1:]))
print("배열의 길이를 모를경우, 마지막 값을 제외한 조회 : {}".format(z[:-1]))
print("인덱스 2 이상의 요소 조회 : {}".format(z[2:]))
print("인덱스 8 미만의 요소 조회 : {}".format(z[:8]))
print("인덱스 2씩 증가하는 값 조회 : {}".format(z[::2]))

배열의 전체 조회 : [0 1 2 3 4 5 6 7 8 9]
인덱스 1 이상 5 미만의 요소 조회 : [1 2 3 4]
배열의 길이를 모를경우, 마지막 값 조회 : [9]
배열의 길이를 모를경우, 마지막 값을 제외한 조회 : [0 1 2 3 4 5 6 7 8]
인덱스 2 이상의 요소 조회 : [2 3 4 5 6 7 8 9]
인덱스 8 미만의 요소 조회 : [0 1 2 3 4 5 6 7]
인덱스 2씩 증가하는 값 조회 : [0 2 4 6 8]


In [39]:
# n차원 배열 slicing
a = np.arange(1,21).reshape(4,5)
print("배열의 전체 조회 : \n{}".format(a[:]))
print("인덱스 0행 이후, 1열 이후의 요소 조회 : \n{}".format(a[1:,2:]))
print("인덱스 1행 이전, 1열 이전 요소 조회 : \n{}".format(a[:1,:1]))
print("인덱스 1행 이전, 2열 이후의 요소 조회 : \n{}".format(a[:1,2:]))
print("배열의 길이를 모를경우, n행 n열의 마지막 값 조회 : \n{}".format(a[-1:,-1:]))

배열의 전체 조회 : 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
인덱스 0행 이후, 1열 이후의 요소 조회 : 
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
인덱스 1행 이전, 1열 이전 요소 조회 : 
[[1]]
인덱스 1행 이전, 2열 이후의 요소 조회 : 
[[3 4 5]]
배열의 길이를 모를경우, n행 n열의 마지막 값 조회 : 
[[20]]


In [43]:
# Boolean indexing
# 배열의 각 요소의 선택 여부를 Boolean mask를 이용하여 지정하는 방식
b = np.arange(1,10)
print(b)
print(b < 5)
print(b >= 5)

[1 2 3 4 5 6 7 8 9]
[ True  True  True  True False False False False False]
[False False False False  True  True  True  True  True]


In [45]:
# 조건에 해당되는 index만 출력
print(b[b < 5])
print(b[b % 2 != 0])

[1 2 3 4]
[1 3 5 7 9]


In [48]:
# Fancy indexing
# 배열의 각 요소 선택을 index 배열을 전달하여 지정하는 방법
c = np.arange(10,20)
print("index 1,3,5에 위치한 값 : {}".format(c[[1,3,5]]))

index 1,3,5에 위치한 값 : [11 13 15]


In [51]:
d = np.arange(1,13,1).reshape(3,4)
# 0행과 2행의 값 조회
print(d[[0,2]])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [55]:
# Index과 Slicing 조합
print(d)
print("=-"*20)
print(d[1:2,2])
print("=-"*20)
print(d[[0,2],2])
print("=-"*20)
print(d[[0,2],:2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[7]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[ 3 11]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
[[ 1  2]
 [ 9 10]]
