# numpy.zeros(size)
* size 크기 만큼의 0행렬을 생성한다.

In [1]:
import numpy as np

In [15]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [16]:
b = np.zeros([2,3])
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c = np.zeros([2,3,4])
c

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])